CREATE TABLE IF NOT EXISTS opd (
    id BIGSERIAL PRIMARY KEY,
    kode_opd VARCHAR(255),
    nama_opd VARCHAR(255),
    tahun INTEGER,
    created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);