CREATE TABLE IF NOT EXISTS "role" (
    id BIGSERIAL PRIMARY KEY,
    role VARCHAR(255) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
