CREATE TABLE IF NOT EXISTS "bidang_urusan" (
    id BIGSERIAL PRIMARY KEY,
    kode_urusan VARCHAR(255) NOT NULL,
    nama_urusan VARCHAR(255) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);