CREATE TABLE IF NOT EXISTS "kegiatan" (
    id BIGSERIAL PRIMARY KEY,
    kode_kegiatan VARCHAR(255) NOT NULL,
    nama_kegiatan VARCHAR(255) NOT NULL,
    tahun VARCHAR(255) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
