// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/indikator-pokin-opd": {
            "get": {
                "description": "Get list of all Indikator Pokin Opd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indikator Pokin Opd"
                ],
                "summary": "List All Indikator Pokin Opd",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.IndikatorPokinOpdResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new Indikator Pokin Opd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indikator Pokin Opd"
                ],
                "summary": "Create Indikator Pokin Opd",
                "parameters": [
                    {
                        "description": "Indikator Pokin Opd Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.IndikatorPokinOpdCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.IndikatorPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/indikator-pokin-opd/{id}": {
            "get": {
                "description": "Get Indikator Pokin Opd detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indikator Pokin Opd"
                ],
                "summary": "Get Indikator Pokin Opd by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Indikator Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.IndikatorPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update existing Indikator Pokin Opd by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indikator Pokin Opd"
                ],
                "summary": "Update Indikator Pokin Opd",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Indikator Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Indikator Pokin Opd Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.IndikatorPokinOpdUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.IndikatorPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete existing Indikator Pokin Opd by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indikator Pokin Opd"
                ],
                "summary": "Delete Indikator Pokin Opd",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Indikator Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.IndikatorPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pokin-opd": {
            "get": {
                "description": "Get list of all Pokin Opd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pokin Opd"
                ],
                "summary": "List All Pokin Opd",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.PokinOpdResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new Pokin Opd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pokin Opd"
                ],
                "summary": "Create Pokin Opd",
                "parameters": [
                    {
                        "description": "Pokin Opd Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PokinOpdCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.PokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pokin-opd/{id}": {
            "get": {
                "description": "Get Pokin Opd detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pokin Opd"
                ],
                "summary": "Get Pokin Opd by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.PokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update existing Pokin Opd by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pokin Opd"
                ],
                "summary": "Update Pokin Opd",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pokin Opd Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PokinOpdUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.PokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete existing Pokin Opd by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pokin Opd"
                ],
                "summary": "Delete Pokin Opd",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.PokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tujuan-pokin-opd": {
            "get": {
                "description": "Get list of all Tujuan Pokin Opd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tujuan Pokin Opd"
                ],
                "summary": "List All Tujuan Pokin Opd",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "kode_opd": {
                                                        "type": "string"
                                                    },
                                                    "tujuan": {
                                                        "type": "string"
                                                    },
                                                    "bidang_urusan": {
                                                        "type": "string"
                                                    },
                                                    "tahun_awal_periode": {
                                                        "type": "integer"
                                                    },
                                                    "tahun_akhir_periode": {
                                                        "type": "integer"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new Tujuan Pokin Opd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tujuan Pokin Opd"
                ],
                "summary": "Create Tujuan Pokin Opd",
                "parameters": [
                    {
                        "description": "Tujuan Pokin Opd Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "kode_opd": {
                                    "type": "string"
                                },
                                "tujuan": {
                                    "type": "string"
                                },
                                "bidang_urusan": {
                                    "type": "string"
                                },
                                "tahun_awal_periode": {
                                    "type": "integer"
                                },
                                "tahun_akhir_periode": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "kode_opd": {
                                                    "type": "string"
                                                },
                                                "tujuan": {
                                                    "type": "string"
                                                },
                                                "bidang_urusan": {
                                                    "type": "string"
                                                },
                                                "tahun_awal_periode": {
                                                    "type": "integer"
                                                },
                                                "tahun_akhir_periode": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tujuan-pokin-opd/{id}": {
            "put": {
                "description": "Update existing Tujuan Pokin Opd by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tujuan Pokin Opd"
                ],
                "summary": "Tujuan Update Pokin Opd",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tujuan Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tujuan Pokin Opd Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": [
                                "id"
                            ],
                            "properties": {
                                "id": {
                                    "type": "integer"
                                },
                                "kode_opd": {
                                    "type": "string"
                                },
                                "tujuan": {
                                    "type": "string"
                                },
                                "bidang_urusan": {
                                    "type": "string"
                                },
                                "tahun_awal_periode": {
                                    "type": "integer"
                                },
                                "tahun_akhir_periode": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "integer"
                                                },
                                                "kode_opd": {
                                                    "type": "string"
                                                },
                                                "tujuan": {
                                                    "type": "string"
                                                },
                                                "bidang_urusan": {
                                                    "type": "string"
                                                },
                                                "tahun_awal_periode": {
                                                    "type": "integer"
                                                },
                                                "tahun_akhir_periode": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "get": {
                "description": "Get Tujuan Pokin Opd detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tujuan Pokin Opd"
                ],
                "summary": "Get Tujuan Pokin Opd by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tujuan Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TujuanPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete existing Tujuan Pokin Opd by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tujuan Pokin Opd"
                ],
                "summary": "Delete Tujuan Pokin Opd",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tujuan Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TujuanPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pohon-kinerja-opd/{kode_opd}/{tahun}": {
            "get": {
                "description": "Get pohon kinerja opd by kode opd and tahun",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pohon Kinerja Opd"
                ],
                "summary": "Get Pohon Kinerja Opd",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kode_opd",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun",
                        "name": "tahun",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.PohonKinerjaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/target-pokin-opd": {
            "get": {
                "description": "Get list of all Target Pokin Opd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Target Pokin Opd"
                ],
                "summary": "List All Target Pokin Opd",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.TargetPokinOpdResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new Target Pokin Opd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Target Pokin Opd"
                ],
                "summary": "Create Target Pokin Opd",
                "parameters": [
                    {
                        "description": "Target Pokin Opd Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.TargetPokinOpdCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TargetPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/target-pokin-opd/{id}": {
            "get": {
                "description": "Get Target Pokin Opd detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Target Pokin Opd"
                ],
                "summary": "Get Target Pokin Opd by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TargetPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update existing Target Pokin Opd by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Target Pokin Opd"
                ],
                "summary": "Update Target Pokin Opd",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Target Pokin Opd Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.TargetPokinOpdUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TargetPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete existing Target Pokin Opd by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Target Pokin Opd"
                ],
                "summary": "Delete Target Pokin Opd",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target Pokin Opd ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TargetPokinOpdResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.IndikatorPokinOpdCreateRequest": {
            "type": "object",
            "properties": {
                "tujuan_pokin_opd_id": {
                    "type": "integer"
                },
                "indikator": {
                    "type": "string"
                }
            }
        },
        "web.PohonKinerjaIndikatorResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "indikator": {
                    "type": "string"
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PohonKinerjaTargetResponse"
                    }
                }
            }
        },
        "web.PohonKinerjaResponse": {
            "type": "object",
            "properties": {
                "kode_opd": {
                    "type": "string"
                },
                "nama_opd": {
                    "type": "string"
                },
                "tahun": {
                    "type": "integer"
                },
                "tujuan_opd": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PohonKinerjaTujuanResponse"
                    }
                },
                "childs": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "web.PohonKinerjaTargetResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "target": {
                    "type": "integer"
                },
                "satuan": {
                    "type": "string"
                }
            }
        },
        "web.PohonKinerjaTujuanResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "tujuan": {
                    "type": "string"
                },
                "bidang_urusan": {
                    "type": "string"
                },
                "tahun_awal_periode": {
                    "type": "integer"
                },
                "tahun_akhir_periode": {
                    "type": "integer"
                },
                "indikator": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PohonKinerjaIndikatorResponse"
                    }
                }
            }
        },
        "web.IndikatorPokinOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "indikator": {
                    "type": "string"
                }
            }
        },
        "web.IndikatorPokinOpdUpdateRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "indikator": {
                    "type": "string"
                }
            }
        },
        "web.PokinOpdCreateRequest": {
            "type": "object",
            "properties": {
                "kode_opd": {
                    "type": "string"
                },
                "nama_opd": {
                    "type": "string"
                },
                "tahun": {
                    "type": "integer"
                }
            }
        },
        "web.PokinOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "nama_opd": {
                    "type": "string"
                },
                "tahun": {
                    "type": "integer"
                }
            }
        },
        "web.PokinOpdUpdateRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "nama_opd": {
                    "type": "string"
                },
                "tahun": {
                    "type": "integer"
                }
            }
        },
        "web.TujuanPokinOpdCreateRequest": {
            "type": "object",
            "properties": {
                "pokin_opd_id": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "tujuan": {
                    "type": "string"
                },
                "bidang_urusan": {
                    "type": "string"
                },
                "tahun_awal_periode": {
                    "type": "integer"
                },
                "tahun_akhir_periode": {
                    "type": "integer"
                }
            }
        },
        "web.TujuanPokinOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "tujuan": {
                    "type": "string"
                },
                "bidang_urusan": {
                    "type": "string"
                },
                "tahun_awal_periode": {
                    "type": "integer"
                },
                "tahun_akhir_periode": {
                    "type": "integer"
                }
            }
        },
        "web.TargetPokinOpdCreateRequest": {
            "type": "object",
            "properties": {
                "indikator_pokin_opd_id": {
                    "type": "integer"
                },
                "target": {
                    "type": "integer"
                },
                "satuan": {
                    "type": "string"
                }
            }
        },
        "web.TargetPokinOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "target": {
                    "type": "integer"
                },
                "satuan": {
                    "type": "string"
                }
            }
        },
        "web.TargetPokinOpdUpdateRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "target": {
                    "type": "integer"
                },
                "satuan": {
                    "type": "string"
                }
            }
        },
        "web.WebResponse": {
            "description": "Web Response",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "${PROD_HOSTNAME}",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Alur Kerja Service API",
	Description:      "API For Alur Kerja Services",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
